### ISSUE TITLE
https://github.com/TencentBlueKing/iam-python-sdk/blob/master/docs/usage.md

### ISSUE THREAD

**Issue by mojocn** [TencentBlueKing/iam-python-sdk#7]
https://github.com/TencentBlueKing/iam-python-sdk/blob/master/docs/usage.md

> 在项目根目录的 support-files/iam/ 中添加 iam migration json 文件    

这一行 link 路径失败

**Comment by wklken** [comment]
fixed, thanks
https://github.com/TencentBlueKing/iam-python-sdk/pull/8/files

**Comment by mojocn** [comment]
这个路径好像不是很全啊,     有没有这个do_migrate.py 的 导入的json文件sample啊

**Comment by mojocn** [comment]
这个链接应该是一个demo json文件吧
